---
abstract: 'Take a quote file and emit a standalone program that spews a random quote'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101310'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-QuoteCC
no_index:
  directory:
    - t
recommends: {}
requires:
  Data::Dump: 0
  Data::Section: 0
  File::Slurp: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Getopt::Dashes: 0
  Template: 0
  YAML::Syck: 0
  namespace::clean: 0
  perl: v5.10
  perl5i::latest: 0
resources:
  Ratings: http://cpanratings.perl.org/d/App-QuoteCC
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-QuoteCC
  homepage: http://search.cpan.org/dist/App-QuoteCC/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avar/app-quotecc
version: 0.02
